### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by Haldoryn** [ashthespy/Atom-LaTeX#214]
I just started Atom again and this error pops up.
I tried reinstalling the package but it did not help. 

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 18.04.2
**Thrown From**: [atom-latex](https://github.com/ashthespy/Atom-LaTeX) package 0.8.10

### Stack Trace

Uncaught SyntaxError: Unexpected token ...

```
At /opt/atom/resources/app/src/native-compile-cache.js:97

SyntaxError: Unexpected token ...
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-latex/node_modules/ws/index.js:3:19)
    at /packages/atom-latex/node_modules/ws/index.js:12:3)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-latex/lib/server.coffee:3:6)
    at /packages/atom-latex/lib/server.coffee:1:1)
    at /packages/atom-latex/lib/server.coffee:1:1)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/opt/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-latex/lib/main.coffee:100:14)
    at Object.lazyLoad (/packages/atom-latex/lib/main.coffee:23:14)
    at /packages/atom-latex/lib/main.coffee:16:30
```

### Commands

```
     -2:40.3.0 core:paste (input.hidden-input)
     -2:03.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-language-r 1.4.8 
atom-latex 0.8.10 
atom-updater-linux 1.3.0 
color-picker 2.3.0 
django-atom 0.2.4 
docker 0.8.0 
file-icons 2.1.33 
highlight-selected 0.16.0 
ide-css 0.3.2 
ide-r 0.1.8 
kite 0.167.0 
language-docker 1.1.8 
latex-itemizer 1.1.1 
latex-tree 0.5.0 
latex-wordcount 0.6.0 
pdf-view 0.71.0 
pigments 0.40.2 
process-palette 0.17.0 
zentabs 0.8.9 
```

**Comment by ashthespy** [comment]
You seem to be on a really old version of Atom (1.26.1 vs [1.39.1](https://github.com/atom/atom/releases/latest)) that has an incompatible node version with the `ws` dependency this packages uses.
