### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /[][\OML/cmm/m/it/10\.aux/: Unterminated charac...

### ISSUE THREAD

**Issue by simenkva** [ashthespy/Atom-LaTeX#217]
I discovered that some overfull hbox cases trigger an error in atom-latex. I have tried to strip down my source as much as possible to trigger the error. I am not experienced enough to understand the error message, but it seems to be something with unexpected syntax in the log file.

1. Compile the following LaTeX file:

```
\documentclass[11pt]{report}
\usepackage{amsthm}
\usepackage[a5paper,left=1cm,right=1cm]{geometry}

\newtheorem{proposition}{Proposition}

\begin{document}
\begin{proposition}
  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx $(\hat{H}[v]\Gamma$
\end{proposition}
\end{document}
```

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [atom-latex](https://github.com/ashthespy/Atom-LaTeX) package 0.8.10

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /[][\OML/cmm/m/it/10\.aux/: Unterminated character class

```
At /Users/simen/.atom/packages/atom-latex/lib/parser.coffee:73

SyntaxError: Invalid regular expression: /[][\OML/cmm/m/it/10\.aux/: Unterminated character class
    at RegExp (<anonymous>)
    at Parser.module.exports.Parser.parseLatex (/packages/atom-latex/lib/parser.coffee:73:30)
    at Parser.module.exports.Parser.parse (/packages/atom-latex/lib/parser.coffee:31:8)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:112:19)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:45:8)
    at /packages/atom-latex/lib/builder.coffee:77:10)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

### Commands

```
  2x -0:36.5.0 core:save (input.hidden-input)
     -0:28.5.0 core:backspace (input.hidden-input)
     -0:28.1.0 editor:newline (input.hidden-input)
  2x -0:27.7.0 core:save (input.hidden-input)
     -0:24.6.0 core:move-down (input.hidden-input)
  5x -0:24.2.0 core:move-up (input.hidden-input)
     -0:23.2.0 core:backspace (input.hidden-input)
     -0:23 editor:newline (input.hidden-input)
     -0:22.7.0 core:save (input.hidden-input)
  4x -0:16.6.0 core:undo (input.hidden-input)
     -0:14.7.0 core:save (input.hidden-input)
     -0:09.2.0 core:move-up (input.hidden-input)
  2x -0:08.8.0 core:move-down (input.hidden-input)
     -0:07.4.0 core:select-down (input.hidden-input)
     -0:06.9.0 core:backspace (input.hidden-input)
     -0:06.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.10 
autocomplete-latex-cite 0.3.2 
figletify 0.2.2 
grammar-token-limit 0.1.1 
language-latex 1.2.0 
latex-autocomplete 1.1.1 
minimap 4.29.9 
pdf-view 0.71.0 
```

**Comment by ashthespy** [comment]
Sorry, I seem to have missed this - will take a look over the weekend!
