### ISSUE TITLE
Uncaught TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by joaquimcampos** [ashthespy/Atom-LaTeX#226]
I installed your package two days ago and everything was running smoothly.

Now, after having rebooted the pc, when I launch the preview tab I get the following error: "Uncaught TypeError: Cannot read property 'send' of undefined".

I do not get an error if I launch the "Preview" instead of the "Preview tab". Therefore,  I have been splitting the screen between the LaTeX code and the "Preview" to achieve the same results.

Details:

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 18.04.3
**Thrown From**: [atom-latex](https://github.com/ashthespy/Atom-LaTeX) package 0.8.11

### Stack Trace

Uncaught TypeError: Cannot read property 'send' of undefined

```
At /home/joaquim/.atom/packages/atom-latex/lib/viewer.coffee:26

TypeError: Cannot read property 'send' of undefined
    at Viewer.module.exports.Viewer.wsHandler (/packages/atom-latex/lib/viewer.coffee:26:20)
    at /packages/atom-latex/lib/server.coffee:25:47)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (/packages/atom-latex/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (/packages/atom-latex/node_modules/ws/lib/receiver.js:423:14)
    at Receiver.getData (/packages/atom-latex/node_modules/ws/lib/receiver.js:353:17)
    at Receiver.startLoop (/packages/atom-latex/node_modules/ws/lib/receiver.js:139:22)
    at Receiver._write (/packages/atom-latex/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Receiver.Writable.write (_stream_writable.js:294:11)
    at Socket.socketOnData (/packages/atom-latex/node_modules/ws/lib/websocket.js:875:35)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
  2x -0:13.8.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:11.3.0 core:save (input.hidden-input)
     -0:07.2.0 command-palette:toggle (input.hidden-input)
     -0:04.3.0 core:move-down (input.hidden-input)
     -0:03.9.0 core:confirm (input.hidden-input)
     -0:03.9.0 atom-latex:preview-tab (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.11 
Hydrogen 2.12.0 
```

**Comment by danielchen26** [comment]
Same error

**Comment by ashthespy** [comment]
@joaquimcampos @danielchen26 I tried a bit to reproduce this, but didn't mange to. Could you give me some detailed steps to reproduce this?

**Comment by maknu1** [comment]
I have same error about some months. 
To reproduce:
- Start System
- Open Atom Editor and some LaTeX Code in splittet view (I have always LaTeX Code on left side)
- Then do "Packages->Atom-LaTeX->Preview PDF in new Tab"
- and then poping up this error.
Thanks for help to solve it.

**Comment by ashthespy** [comment]
Found the issue, fix coming up.

**Comment by hallsville3** [comment]
I have the same problem as @maknu1.
I'm using the latest nightly build of Atom.

**Comment by ashthespy** [comment]
Closing this in favour of #245
