### ISSUE TITLE
Uncaught TypeError: Cannot read property 'markBufferRange' of undefined

### ISSUE THREAD

**Issue by casv2** [ashthespy/Atom-LaTeX#235]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.43.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [atom-latex](https://github.com/ashthespy/Atom-LaTeX) package 0.8.11

### Stack Trace

Uncaught TypeError: Cannot read property 'markBufferRange' of undefined

```
At /Users/Cas/.atom/packages/atom-latex/lib/locator.coffee:76

TypeError: Cannot read property 'markBufferRange' of undefined
    at /packages/atom-latex/lib/locator.coffee:76:25
    at ChildProcess.exithandler (child_process.js:290:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```

### Commands

```
     -3:57.4.0 core:move-up (input.hidden-input)
  2x -3:57 core:move-down (input.hidden-input)
  5x -3:56.3.0 core:move-up (input.hidden-input)
     -3:54.9.0 core:move-left (input.hidden-input)
     -3:54.6.0 core:backspace (input.hidden-input)
  5x -3:54.2.0 core:move-down (input.hidden-input)
  2x -3:53 editor:newline (input.hidden-input)
  2x -1:17.9.0 core:backspace (input.hidden-input)
  2x -1:09.0 editor:newline (input.hidden-input)
     -1:08.7.0 core:move-up (input.hidden-input)
  2x -1:05.1.0 core:backspace (input.hidden-input)
  2x -1:04.6.0 editor:newline (input.hidden-input)
     -1:01.3.0 autocomplete-plus:confirmIfNonDefault (input.hidden-input)
  2x -1:01.3.0 editor:newline (input.hidden-input)
     -0:40.5.0 editor:toggle-line-comments (input.hidden-input)
  2x -0:34.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.11 
ftp-remote-edit 0.17.4 
Hydrogen 2.13.0 
indent-detective 0.4.0 
ink 0.11.5 
julia-client 0.11.2 
language-julia 0.19.1 
latex-completions 0.3.6 
remote-atom 1.3.12 
remote-sync 4.1.8 
script 3.18.1 
terminal-tab 0.5.7 
tool-bar 1.2.0 
uber-juno 0.3.0 
```

**Comment by ashthespy** [comment]
Greetings, could you please provide detailed steps to reproduce the error as well?
