### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by joshallen28** [ashthespy/Atom-LaTeX#246]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.5
**Thrown From**: [atom-latex](https://github.com/ashthespy/Atom-LaTeX) package 0.9.1

### Stack Trace

Uncaught TypeError: Cannot read property '1' of undefined

```
At /Users/joshuaallen/.atom/packages/atom-latex/lib/manager.coffee:162

TypeError: Cannot read property '1' of undefined
    at Manager.module.exports.Manager.findPDF (/packages/atom-latex/lib/manager.coffee:162:59)
    at Viewer.module.exports.Viewer.openViewerNewWindow (/packages/atom-latex/lib/viewer.coffee:84:30)
    at Viewer.module.exports.Viewer.openViewer (/packages/atom-latex/lib/viewer.coffee:74:8)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:126:21)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:45:8)
    at /packages/atom-latex/lib/builder.coffee:77:10)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -4:25 core:select-all (input.hidden-input)
     -4:24.1.0 core:copy (input.hidden-input)
     -4:21.2.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -4:20.2.0 core:paste (input.hidden-input)
     -4:17.9.0 core:save (input.hidden-input)
  2x -4:08.0 editor:move-to-previous-subword-boundary (input.hidden-input)
 11x -3:05.5.0 core:backspace (input.hidden-input)
     -2:43.2.0 core:copy (input.hidden-input)
     -2:42.2.0 application:new-file (input.hidden-input)
     -2:41 core:paste (input.hidden-input)
     -2:39.4.0 core:save (input.hidden-input)
  9x -1:31.7.0 core:move-left (input.hidden-input)
     -1:28.1.0 core:move-down (input.hidden-input)
     -1:22.2.0 core:save (input.hidden-input)
     -1:13.9.0 editor:move-to-previous-subword-boundary (input.hidden-input)
  2x -0:38.4.0 core:move-left (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.9.1 
language-latex 1.2.0 
latex 0.50.2 
latex-autocomplete 1.1.1 
latex-wordcount 0.6.0 
latextools 0.8.5 
pdf-view 0.72.0 
typewriter 0.8.0 
```

**Comment by ashthespy** [comment]
Please provide steps to reproduce as well, else there isn't much I can do..

**Comment by huatanshaonian** [comment]
I have a similar problem
Uncaught TypeError: Cannot read property '1' of undefined

/home/huatanshaonian/.atom/packages/atom-latex/lib/manager.coffee:162
Hide Stack Trace
TypeError: Cannot read property '1' of undefined
    at Manager.module.exports.Manager.findPDF (/home/huatanshaonian/.atom/packages/atom-latex/lib/manager.coffee:162:59)
    at Viewer.module.exports.Viewer.openViewerNewWindow (/home/huatanshaonian/.atom/packages/atom-latex/lib/viewer.coffee:84:30)
    at Viewer.module.exports.Viewer.openViewer (/home/huatanshaonian/.atom/packages/atom-latex/lib/viewer.coffee:74:8)
    at Builder.module.exports.Builder.postBuild (/home/huatanshaonian/.atom/packages/atom-latex/lib/builder.coffee:126:21)
    at Builder.module.exports.Builder.buildProcess (/home/huatanshaonian/.atom/packages/atom-latex/lib/builder.coffee:45:8)
    at ChildProcess.<anonymous> (/home/huatanshaonian/.atom/packages/atom-latex/lib/builder.coffee:77:10)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)

**Comment by ashthespy** [comment]
Closing this, feel free to chime in to reopen it..

**Comment by kapitaali** [comment]
I came to this page from my Atom editor, trying to compile a latex letter sources [taken from here.](https://www.maths.ox.ac.uk/members/it/faqs/latex/letters) 

What I did was:
1. Download the file https://www.maths.ox.ac.uk/system/files/legacy/2691/oxmathletter.cls to a new directory
2. Create file essay.latex, its content being the few lines of a LaTeX letter [on this page.](https://www.maths.ox.ac.uk/members/it/faqs/latex/letters)
3. Set working directory to the dir that contains the 2 files (essay.latex, oxmathletter.cls)
4. Clear aux files
5. Build LaTeX from active editor

Get error:

```/home/theb/.atom/packages/atom-latex/lib/manager.coffee:159
Hide Stack Trace
TypeError: Cannot read property '1' of undefined
    at Manager.module.exports.Manager.findPDF (/home/theb/.atom/packages/atom-latex/lib/manager.coffee:159:59)
    at Viewer.module.exports.Viewer.openViewerNewWindow (/home/theb/.atom/packages/atom-latex/lib/viewer.coffee:83:30)
    at Viewer.module.exports.Viewer.openViewer (/home/theb/.atom/packages/atom-latex/lib/viewer.coffee:73:8)
    at Builder.module.exports.Builder.postBuild (/home/theb/.atom/packages/atom-latex/lib/builder.coffee:126:21)
    at Builder.module.exports.Builder.buildProcess (/home/theb/.atom/packages/atom-latex/lib/builder.coffee:45:8)
    at ChildProcess.<anonymous> (/home/theb/.atom/packages/atom-latex/lib/builder.coffee:77:10)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)```

**Comment by ashthespy** [comment]
@kapitaali  
-- How do you set your [root document](https://github.com/ashthespy/Atom-LaTeX#setting-the-latex-root-file)?
-- Any interesting messages on the dev console?
