### ISSUE TITLE
Uncaught Error: Cannot find module 'hasbin'

### ISSUE THREAD

**Issue by anellenson** [ashthespy/Atom-LaTeX#290]
[Enter steps to reproduce:]

1. open latex project

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.15.6
**Thrown From**: [atom-latex](https://github.com/ashthespy/Atom-LaTeX) package 0.9.1

### Stack Trace

Uncaught Error: Cannot find module 'hasbin'

```
At internal/modules/cjs/loader.js:604

Error: Cannot find module 'hasbin'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/private/var/folders/xf/kh39r1cj1qx84jb4h6xkv1840000gn/T/AppTranslocation/CE9E154D-4BB4-499D-909D-C3A1DE397AE4/d/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/private/var/folders/xf/kh39r1cj1qx84jb4h6xkv1840000gn/T/AppTranslocation/CE9E154D-4BB4-499D-909D-C3A1DE397AE4/d/Atom.app/Contents/Resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/private/var/folders/xf/kh39r1cj1qx84jb4h6xkv1840000gn/T/AppTranslocation/CE9E154D-4BB4-499D-909D-C3A1DE397AE4/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Atom-LaTeX/lib/builder.coffee:4:6)
    at /packages/Atom-LaTeX/lib/builder.coffee:1:1)
    at /packages/Atom-LaTeX/lib/builder.coffee:1:1)
    at Module.get_Module._compile (/private/var/folders/xf/kh39r1cj1qx84jb4h6xkv1840000gn/T/AppTranslocation/CE9E154D-4BB4-499D-909D-C3A1DE397AE4/d/Atom.app/Contents/Resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/private/var/folders/xf/kh39r1cj1qx84jb4h6xkv1840000gn/T/AppTranslocation/CE9E154D-4BB4-499D-909D-C3A1DE397AE4/d/Atom.app/Contents/Resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/private/var/folders/xf/kh39r1cj1qx84jb4h6xkv1840000gn/T/AppTranslocation/CE9E154D-4BB4-499D-909D-C3A1DE397AE4/d/Atom.app/Contents/Resources/app/static/<embedded>:11:146745)
    at /packages/Atom-LaTeX/lib/main.coffee:100:15)
    at Object.lazyLoad (/packages/Atom-LaTeX/lib/main.coffee:23:14)
    at /packages/Atom-LaTeX/lib/main.coffee:16:30
```

### Commands

```
  2x -4:33.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-latex 0.9.1 
autocomplete-python 1.16.0 
busy-signal 2.0.1 
django-templates 0.5.0 
intentions 1.1.5 
linter 2.3.1 
linter-flake8 2.4.0 
linter-ui-default 1.6.8 
markdown-preview-plus 3.10.0 
```

**Comment by ashthespy** [comment]
>Atom: 1.40.1 x64

You should probably upgrade and/or check your plugin installation.

**Comment by anellenson** [comment]
Thanks, will try
